[project]
name = "usdcx-integration-studio"
description = "USDCx Integration Studio Contracts"
authors = []
telemetry = true
cache_dir = "./.cache"
requirements = []
[contracts.traits]
path = "contracts/traits.clar"
clarity_version = 2
epoch = 2.5

[contracts.usdcx-escrow]
path = "contracts/usdcx-escrow.clar"
clarity_version = 2
epoch = 2.5
depends_on = ["traits"]
[repl]
cost_abstraction = true
[analysis]
passes = ["check_checker"]

[analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
